# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('heigth', models.IntegerField()),
                ('image', models.ImageField(height_field='height', upload_to='maps/', width_field='width')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('coordinate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Coordinate')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Floor')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('map', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Map')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.MapImage'),
        ),
        migrations.AddField(
            model_name='map',
            name='start_coordinate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Coordinate'),
        ),
        migrations.AddField(
            model_name='floor',
            name='map',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Map'),
        ),
        migrations.AddField(
            model_name='building',
            name='coordinate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Coordinate'),
        ),
        migrations.AddField(
            model_name='building',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Scheme'),
        ),
    ]
