# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapimage',
            name='heigth',
        ),
        migrations.RemoveField(
            model_name='mapimage',
            name='width',
        ),
        migrations.AlterField(
            model_name='mapimage',
            name='image',
            field=models.ImageField(upload_to='maps/'),
        ),
    ]
