# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171020_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='path_to_graph',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
