# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171027_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='api.Scheme'),
        ),
    ]
