# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 09:08
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171116_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='name',
        ),
        migrations.RemoveField(
            model_name='map',
            name='path_to_graph',
        ),
        migrations.AlterField(
            model_name='map',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, size=[1080, 608], upload_to='maps'),
        ),
        migrations.DeleteModel(
            name='MapImage',
        ),
    ]
