# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171122_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinate',
            old_name='latitude',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='coordinate',
            old_name='longitude',
            new_name='y',
        ),
    ]
