# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171123_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='isPassageway',
        ),
        migrations.AddField(
            model_name='building',
            name='passagewayFloorNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passageway',
            name='toBuildingId',
            field=models.IntegerField(default=None),
        ),
    ]
